### ISSUE TITLE
use storybook with vue and vue-i18n

### ISSUE THREAD

**Issue by sky790312** [storybooks/storybook#1573]
my component combines with vue-i18n. I try to add like this:

import Vue from 'vue'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)

but it still can't work in storybook. How to use it ?

**Comment by ndelangen** [comment]
Move the code into the `config.js`:

```
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)
```

See the veux example here:
https://github.com/storybooks/storybook/blob/master/examples/vue-kitchen-sink/.storybook/config.js#L9

**Comment by sky790312** [comment]
I use it in config.js. But it doenn't work.
In vue, the completed usage is like:

```
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import locales from '../src/locales'

Vue.use(VueI18n)
const i18n = new VueI18n({
   locale: 'zh-tw',
   messages: locales,
   silentTranslationWarn: true
})

const app = new Vue({
   el: '#app',
   i18n,
   render: h => h(App)
})
```

But I don't know how to setting this in storybook

**Comment by kazupon** [comment]
In the same way as vuex, You need to use the `VueI18n` instance in the story

See the vuex story example here:
https://github.com/storybooks/storybook/blob/master/examples/vue-kitchen-sink/src/stories/index.js

**Comment by alexcheninfo** [comment]
@kazupon Could you please provide a short example? ` store: new Vuex.Store` uses `new`. So it's a bit confusing how to use the `VueI18n` instance in the story.

**Comment by kazupon** [comment]
I tried it at storybook.
it does not work.
Hmm 🤔 I'll try to support due to work at storybook.

**Comment by kazupon** [comment]
fixed, and I provided the storybook example.
please check vue-i18n v7.1.1

https://github.com/kazupon/vue-i18n/tree/dev/examples/storybook

**Comment by sky790312** [comment]
awosome! Thanks.

**Comment by maeh2k** [comment]
Hi @kazupon,
I have an issue with vue-i18n in storybook even though I followed the example https://github.com/kazupon/vue-i18n/tree/dev/examples/storybook
I changed the .config and added the i18n in the story itself.

However, the i18n from the story is not passed into the component.
Instead the component appears to create a default i18n with locale en-US and no root i18n.


Do you have any intuition why that problem might occur?

**Comment by alexander-elgin** [comment]
If you use Vue CLI plugin for storybook you can modify the `config/storybook/config.js` as follows

```
import { addDecorator } from '@storybook/vue';
import i18n from '@/plugins/i18n';

addDecorator(() => ({
  template: '<story/>',
  i18n,
}));
```

**Comment by NefixEstrada** [comment]
Thank you, @alexander-elgin !!

I've been searching a solution for this plugin but was unable to make it work. It would be really nice to add this to the Vue documentation with a small example, since I'm sure there are lots of packages that need to be used like this.

**Comment by graup** [comment]
This still doesn't work with Single File Components that rely on the root fallback: https://github.com/dlucian/vuejs-storybook-i18n/issues/1

**Comment by azurinspire** [comment]
If any one is searching solution for Storybook & Vue3 & vue-i18n, just add this to .storybook/preview.js:

```js
import { app } from '@storybook/vue3'
import { createI18n } from 'vue-i18n';
import messages from 'messages';

const i18n = createI18n({
  locale: 'fi',
  fallbackLocale: 'en',
  messages,
});

app.use(i18n)
```

**Comment by doutatsu** [comment]
Does anyone know how to make thsi work for Vue 2 and Storybook 6? I've been trying various things in `preview.js`, including solutions mentioned here, but with no success:

![image](https://user-images.githubusercontent.com/4270980/114930845-64652800-9e2d-11eb-87a7-97a094a22336.png)

```js
// preview.js
import Vue from 'vue';
import Vuex from 'vuex';
import VueI18n from 'vue-i18n';
import Vuelidate from 'vuelidate';
import VueScreen from 'vue-screen';
import VueTippy from 'vue-tippy';
import Vue2TouchEvents from 'vue2-touch-events';
import VueScrollTo from 'vue-scrollto';
import Meta from 'vue-meta';
import { Loading } from 'element-ui';

import '@/stylesheets/tailwind.css';
import '@/stylesheets/global.scss';
import '@/stylesheets/transitions.scss';

import '../../src/components/_globals';
import store from '@/store';

Vue.use(Vuex);
Vue.use(Vuelidate);
Vue.use(VueI18n);
Vue.use(Loading);
Vue.use(VueScrollTo);
Vue.use(Meta);
Vue.use(VueScreen, {
  extend: 'tailwind',
  mobile: (screen) => screen.xs || screen.sm,
  tablet: (screen) => screen.xs || screen.sm || screen.md,
  desktop: (screen) => screen.lg || screen.xl,
});
Vue.use(VueTippy, {
  directive: 'tippy',
  animateFill: false,
  animation: 'shift-toward',
  theme: 'light',
});
Vue.use(Vue2TouchEvents, {
  disableClick: true,
  touchHoldTolerance: 300,
});

Vue.prototype.$store = store;

global.storyBookVue = Vue;
global.storyBookVueX = Vuex;

```

**Comment by soundyogi** [comment]
> If any one is searching solution for Storybook & Vue3 & vue-i18n, just add this to .storybook/preview.js:
> 
> ```js
> import { app } from '@storybook/vue3'
> import { createI18n } from 'vue-i18n';
> import messages from 'messages';
> 
> const i18n = createI18n({
>   locale: 'fi',
>   fallbackLocale: 'en',
>   messages,
> });
> 
> app.use(i18n)
> ```

this needs to be in the docs

**Comment by shilman** [comment]
cc @jonniebigodes ☝️  not sure i agree, but FYI

**Comment by tillsanders** [comment]
# Vue 2 + Webpack 4 + YAML

For the record – this is how I did it in 2021/09 (storybook/vue v6.1.11) **with Vue 2, Webpack 4 and YAML**. Took me a few hours to figure this out. More examples for use-cases like this would have helped.

## 1. Install `yaml-loader` and add it to the webpack configuration:

```javascript
// .storybook/main.js

module.exports = {
  // ...
  webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.ya?ml$/,
      use: 'yaml-loader',
      type: 'json'
    });
    config.resolve.extensions.push('.yaml');
    return config;
  },
}
```

## 2. Add typings:

```typescript
// yaml-shims.d.ts

declare module '*.yaml' {
  const data: unknown;
  export default data;
}
```

## 3. Load VueI18n and locales:

```javascript
// .storybook/preview.js

import VueI18n from 'vue-i18n';
import enLocale from '../src/locales/en.yaml'

const i18n = new VueI18n({
  locale: 'en',
  fallbackLocale: 'en',
  messages: {
    en: enLocale,
  },
});

// This looks like it doesn't do anything, but I kept it since it would technically be the standard
// way to do this. What really did the trick though was the decorator.
Vue.extend({ i18n });

export const decorators = [(story) => ({
  components: { story },
  i18n, // this is the essential part to have t() and Co. in your components
  template: '<story />'
})];
```

**(4. Add your locales to src/locales/*.yaml)**

**Comment by allanlewis** [comment]
> For the record – this is how I did it in 2021/09...

@tillsanders I have a very similar setup to you - Vue 2, Storybook 6.1, but locales in JSON so I don't need `yaml-loader` - but your config above wasn't working for me until I added `Vue.use(VueI18n)` before instantiating `VueI18n`.

Without that change I get this console error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'config')
    at VueI18n._initVM (vue-i18n.esm.js:1350:1)
    at new VueI18n (vue-i18n.esm.js:1289:1)
    at Module../.storybook/preview.js (preview.js:13:1)
...
```

Hopefully this helps someone experiencing the same issue!

**Comment by 1c7** [comment]
# For Vue.js 2 & Storybok 6.4
Here is how to use `vue-i18n` in Storybook. without having `$t` or `config` error.

## File: `package.json`
Here is exact version
```
{
  "dependencies": {
    "vue": "^2.6.14"
  },
  "devDependencies": {
    "@storybook/vue": "^6.4.21"
  }
}
```

# `.storybook/preview.js`
```javascript
import VueI18n from 'vue-i18n';
Vue.use(VueI18n);

const messages = {
  en: {
    message: {
      hello: "{msg} world",
    },
  },
};
const i18n = new VueI18n({
  locale: "en",
  fallbackLocale: "en",
  messages,
});

Vue.prototype.$t = function(...args){
  return i18n.t(...args);
}
```

Works for me.

**Comment by mszkb** [comment]
If you use Vue CLI and added i18n with `vue add i18n`, then you only need to do in your **preview.js**:

```
import i18n from '../../src/i18n'

Vue.prototype.$t = function(...args){
  return i18n.t(...args);
}
```

replace '../../src/i18n' with path to your i18n.js file.

**Comment by MattFromGer** [comment]
With vite and Storybook v7:

`preview.ts`
```typescript
import i18n from "../src/plugins/i18n";
import { setup } from "@storybook/vue3";

setup((app) => {
  app.use(i18n);
});
```
assuming your i18n config is defined in the /plugins folder

**Comment by Horlamedhey** [comment]
> With vite and Storybook v7:
> 
> `preview.js`
> 
> ```js
> import i18n from "../src/plugins/i18n";
> import { setup } from "@storybook/vue3";
> 
> setup((app) => {
>   app.use(i18n);
> });
> ```
> 
> assuming your i18n config is defined in the /plugins folder

I'm getting an error; "_a.decline is not a function"

**Comment by vhovorun** [comment]
@Horlamedhey Getting the same issue, have you managed to come with some solution for that?

**Comment by Horlamedhey** [comment]
Yes actually
Add this
`config.define = {
      module: { hot: null },
    }`
    immediately before returning 'config' in your '.storybook/main.js' file

**Comment by vhovorun** [comment]
@Horlamedhey thanks, I've tried your solution but still getting this error(((

**Comment by Horlamedhey** [comment]
Hmm... I really don't know what else it could be`

**Comment by vhovorun** [comment]
I've noticed that this issue is getting only when 'storybook-addon-nuxt' is using, without it it works correctly

**Comment by Walnussbaer** [comment]
> With vite and Storybook v7:
> 
> `preview.js`
> 
> ```js
> import i18n from "../src/plugins/i18n";
> import { setup } from "@storybook/vue3";
> 
> setup((app) => {
>   app.use(i18n);
> });
> ```
> 
> assuming your i18n config is defined in the /plugins folder

Works perfectly with Vue3, Vite and Storybook 7.5
