### ISSUE TITLE
TypeError: assign is not a function

### ISSUE THREAD

**Issue by GozuPro** [storybooks/storybook#3807]
### Bug or support request summary

`npm run storybook` fails on CRNA project because assign is not a function.  
I tried to compile with node 6.0.0 or 8.3.0. Is there something I need to install to fix this issue as a global polyfill? Is it possible to use Storybook 3.0 and maybe not an alpha version? 

```
TypeError: assign is not a function
    at Object.<anonymous> (....node_modules/@storybook/core/server.js:7:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...node_modules/@storybook/react-native/dist/server/config/webpack.config.js:35:15)
    at Module._compile (module.js:541:32)
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react-native 4.0.0-alpha.10x.x.x
- @storybook/addons 4.0.0-alpha.10x.x.x

**Comment by igor-dv** [comment]
Do you have a `babel-runtime` installed?

**Comment by GozuPro** [comment]
Thanks for your help @igor-dv but I did not. Apparently, this package is not automatically installed after `create-react-native-app`. That being said, after running `npm install babel-runtime` followed by `npm run storybook`,  I end up with the following different error:  

```> storybook start -p 7007
sh: storybook: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! Example@0.1.0 storybook: `storybook start -p 7007`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the Example@0.1.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    .../.npm/_logs/2018-06-27T22_34_52_493Z-debug.log
```

In package.json, I have the following under scripts:

```
"scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest",
    "storybook": "storybook start -p 7007"
},
```

What's surprising for me is I'm able to do `npm run start` without any issue.

**Comment by DylanMay** [comment]
same issue

![image](https://user-images.githubusercontent.com/1918144/42020000-35ce1052-7ae9-11e8-8198-1ffec177835e.png)
npm: v6.1.0
webpack: 4.12.2
node: v8.11.2

**Comment by igor-dv** [comment]
@GozuPro , looks like the storybook package script is wrong for you. There was a similar issue here #1726, please take a look.

Regarding the `assign` problem, storybook has a peer deps on babel-core and babel-runtime. please check that you have these deps installed.

**Comment by GozuPro** [comment]
@igor-dv, looks like the README.md is incomplete or the 4.0.0-alpha version isn't ready.
I started from scratch with the following:

```
npm i -g create-react-native-app
create-react-native-app my-project
cd my-project
npm start
npm i -g @storybook/cli
getstorybook
npm run storybook
```
As described, I updated App.js to contain the following: `export default from './storybook';`

From there, I even tried the following without success:

```
npm install babel-runtime
npm install babel-preset-es2015
npm install babel-preset-stage-2
npm install babel-core
```

What should I do because I'm losing patience on your promising package. Is someone able to create a CRNA project with Storybook version 4.0 working? 

Thanks

**Comment by igor-dv** [comment]
For the alpha version you should use an alpha version of the cli as well

**Comment by dedan** [comment]
I'm having the same issue, did anyone figure out a solution?

**Comment by maggy96** [comment]
Same here, any progress?

**Comment by dedan** [comment]
I solved it by doing a manual installation of version 3.x following these
instrutions: https://storybook.js.org/basics/guide-react/

**Comment by xfumihiro** [comment]
be sure to install babel-runtime v6 (instead of v7)
which is storybook depends on
