### ISSUE TITLE
Storybook 5, typescript .addDecorator addon-info

### ISSUE THREAD

**Issue by volkerchartier** [storybooks/storybook#5989]
After updating to 5.0.0 and adding 

`import { configure, addDecorator} from '@storybook/react';`
`import {withInfo} from '@storybook/addon-info';`
`addDecorator(withInfo );`

to my .storybook/config.tsx file ends in empty story and following error in console output

**To Reproduce**
1. create a Storybook 5.0.0 React/Typescript project
2. addDecorator 

`
Uncaught TypeError: _react.default.memo is not a function
    at Object../node_modules/@storybook/addon-info/node_modules/@storybook/components/dist/tabs/tabs.js (vendors~main.73e5392714a08d36fe86.bundle.js:8137)
    at __webpack_require__ (runtime~main.73e5392714a08d36fe86.bundle.js:782)
    at fn (runtime~main.73e5392714a08d36fe86.bundle.js:150)
    at Object../node_modules/@storybook/addon-info/node_modules/@storybook/components/dist/index.js (vendors~main.73e5392714a08d36fe86.bundle.js:7410)
    at __webpack_require__ (runtime~main.73e5392714a08d36fe86.bundle.js:782)
    at fn (runtime~main.73e5392714a08d36fe86.bundle.js:150)
    at Object../node_modules/@storybook/addon-info/dist/components/markdown/code.js (vendors~main.73e5392714a08d36fe86.bundle.js:3905)
    at __webpack_require__ (runtime~main.73e5392714a08d36fe86.bundle.js:782)
    at fn (runtime~main.73e5392714a08d36fe86.bundle.js:150)
    at Object../node_modules/@storybook/addon-info/dist/components/markdown/index.js (vendors~main.73e5392714a08d36fe86.bundle.js:4188)
`

**Expected behavior**
No Errors, no empty stories

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: [e.g. react, vue, angular]
 - Addons: Add-info
 - Version: [e.g. 5.0.0]

**Additional context**
Typescript + React

**Comment by shilman** [comment]
What version of react are you running?

**Comment by volkerchartier** [comment]
@shilman React Version was 16.6.3 now running on 16.8.x ending in some typings errors but addDecorator + addon-info is running under storybook 5.0.1.

**Comment by shilman** [comment]
I think it's still a bug since `addon-info` shouldn't use new features of React.

**Comment by Jony-Y** [comment]
having the same issue.

**Comment by volkerchartier** [comment]
@shilman
` npx ncu '/@types/' -u && npm i` definitely solves my problem.

**Comment by shilman** [comment]
@volkerchartier but you also had to upgrade react, and that's a problem

**Comment by volkerchartier** [comment]
@shilman I´m not 100% sure.  I use your first response here as hint to update React. Finally updating types solves the problem...

**Comment by maeligg** [comment]
I encountered the same issue on a non-TS project using React 16.4.0. I had to update to 16.6.0 (the version where React.memo was added) to make it work.
