### ISSUE TITLE
5.1.0-alpha.7 errors while doing yarn storybook

### ISSUE THREAD

**Issue by limaAniceto** [storybooks/storybook#6702]
Hi,
Really appreciate your work on storybook! We've upgraded to 5.1.0-alpha.7 from 5.0.11, package.json:
```
        "@storybook/react": "5.1.0-alpha.7",
        "@storybook/addon-actions": "5.1.0-alpha.7",
        "@storybook/addon-links": "5.1.0-alpha.7",
        "@storybook/addons": "5.1.0-alpha.7"
```

We are getting the following errors while doing `yarn storybook`:
```
Miguels-MacBook:js aniceto$ yarn storybook
yarn run v1.9.4
$ start-storybook -p 6006
info @storybook/react v5.1.0-alpha.7
info
info => Loading presets
WARN   Failed to load preset: "/Volumes/Workspace/TMP/website/js/node_modules/@storybook/core/dist/server/manager/manager-preset.js"
ERR! Error: Cannot find module 'emotion-theming/package.json'
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:30:19)
ERR!     at Object.<anonymous> (/Volumes/Workspace/Mixcloud/website/js/node_modules/@storybook/ui/paths.js:16:38)
ERR!     at Module._compile (internal/modules/cjs/loader.js:689:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:599:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:637:17)
ERR!     at require (internal/modules/cjs/helpers.js:20:18)
ERR!     at Object.<anonymous> (/Volumes/Workspace/TMP/website/js/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:18:37)
ERR!     at Module._compile (internal/modules/cjs/loader.js:689:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:599:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
ERR!  { Error: Cannot find module 'emotion-theming/package.json'
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:30:19)
ERR!     at Object.<anonymous> (/Volumes/Workspace/Mixcloud/website/js/node_modules/@storybook/ui/paths.js:16:38)
ERR!     at Module._compile (internal/modules/cjs/loader.js:689:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:599:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:637:17)
ERR!     at require (internal/modules/cjs/helpers.js:20:18)
ERR!     at Object.<anonymous> (/Volumes/Workspace/Mixcloud/website/js/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:18:37)
ERR!     at Module._compile (internal/modules/cjs/loader.js:689:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:599:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
ERR!   stack:
ERR!    'Error: Cannot find module \'emotion-theming/package.json\'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.resolve (internal/modules/cjs/helpers.js:30:19)\n    at Object.<anonymous> (/Volumes/Workspace/Mixcloud/website/js/node_modules/@storybook/ui/paths.js:16:38)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/Volumes/Workspace/TMP/website/js/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:18:37)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)',
ERR!   code: 'MODULE_NOT_FOUND' }
info => Loading presets
info => Loading custom webpack config (extending mode).
info => Using base config because react-scripts is not installed.
 10% building 1/1 modules 0 active(node:74699) DeprecationWarning: Extend-mode configuration is deprecated, please use full-control mode instead.

See https://storybook.js.org/docs/configurations/custom-webpack-config/#full-control-mode
```

Any help would be much appreciated!

**Comment by arturgaik** [comment]
Why has this been closed?
