### ISSUE TITLE
After bump up version to 4.0.0-alpha.15, got errors

### ISSUE THREAD

**Issue by ryancat** [storybooks/storybook#4266]
### Bug or support request summary

I bumped up to @storybook/html v4.0.0-alpha.15 and corresponding addons. I was trying to use the new radios knob. After that I get some errors while running start storybook

### Steps to reproduce
Just bump up version and compile

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/html 4.0.0-alpha.15
- @storybook/addon-knobs 4.0.0-alpha.15

### Screenshots / Screencast / Code Snippets (Optional)

```js
$ npm run storybook

> aurora-storybook@1.0.0 storybook /Users/xin.chen/code/aurora/storybook
> start-storybook -p 8001 -c .storybook

info @storybook/html v4.0.0-alpha.15
info
info => Loading custom addons config.
info => Using default webpack setup.
/Users/xin.chen/code/aurora/storybook/node_modules/react-dev-utils/InterpolateHtmlPlugin.js:28
        .getHooks(compilation)
         ^

TypeError: this.htmlWebpackPlugin.getHooks is not a function
    at compiler.hooks.compilation.tap.compilation (/Users/xin.chen/code/aurora/storybook/node_modules/react-dev-utils/InterpolateHtmlPlugin.js:28:10)
    at SyncHook.eval [as call] (eval at create (/Users/xin.chen/code/aurora/storybook/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (/Users/xin.chen/code/aurora/storybook/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/xin.chen/code/aurora/storybook/node_modules/webpack/lib/Compiler.js:498:26)
    at hooks.beforeCompile.callAsync.err (/Users/xin.chen/code/aurora/storybook/node_modules/webpack/lib/Compiler.js:534:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/xin.chen/code/aurora/storybook/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/xin.chen/code/aurora/storybook/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/xin.chen/code/aurora/storybook/node_modules/webpack/lib/Compiler.js:529:28)
    at compiler.hooks.watchRun.callAsync.err (/Users/xin.chen/code/aurora/storybook/node_modules/webpack/lib/Watching.js:77:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/xin.chen/code/aurora/storybook/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
```

**Comment by ndelangen** [comment]
InterpolateHtmlPlugin has to be updated
