### ISSUE TITLE
Upgrading from Storybook 4.1.13 to 5.0.0 - Cannot find module '@emotion/core/package.json'

### ISSUE THREAD

**Issue by sargant** [storybooks/storybook#5942]
**Describe the bug**

When upgrading from Storybook 4.1.13 to 5.0.0, an attempt to run `start-storybook` results in the error message `Error: Cannot find module '@emotion/core/package.json`.

There is no `node_modules/@emotion/core` folder. The only copy that gets installed is due to the dependencies within `@storybook/theming@5.0.0`, so it's not at the top-level `node_modules` folder, but instead at `node_modules/@storybook/theming/node_modules/@emotion/core`.

**To Reproduce**
1. Start with the following dependencies:
```
@storybook/addon-actions@4.1.13
@storybook/addon-knobs@4.1.13
@storybook/addon-options@4.1.13
@storybook/addon-storyshots@4.1.13
@storybook/react@4.1.13
```
2. Upgrade to Storybook 5:
```
> yarn remove @storybook/addon-options
> yarn upgrade --latest @storybook/react @storybook/addon-actions 
      @storybook/addon-knobs @storybook/@addon-storyshots
> yarn add --dev --exact @babel/core babel-loader
```
3. Attempt to start Storybook
```
> yarn run start-storybook -- -p 9001
```

**Environment**
```
Windows 10
node 10.15.0
yarn 1.13.0
```

**Additional context**
Removing `yarn.lock` and `node_modules` and reinstalling purely from the `package.json` file also fails.

**Comment by sargant** [comment]
Note that installing `@storybook/theming` fixes the error - is this package now mandatory?

**Comment by shilman** [comment]
Should not be mandatory. We're still trying to get to the bottom of this -- feels like a yarn bug, but it's all pretty opaque. `@emotion/core` and `@storybook/theming` are def in your dependency tree, but they are just not getting hoisted properly AFAIK.

**Comment by viktormill** [comment]
Im getting the exactly same error with npm and package-lock. `Error: Cannot find module '@emotion/core/package.json'`

**Comment by shilman** [comment]
Resolving this as a duplicate to https://github.com/storybooks/storybook/issues/5919

We still don't know what's going on tho
